#%RAML 1.0 NamedExample
value:
   - 
    ID: 12
    Name: Mr
    Type: personal
    Address:
      streetAddress: 123 Green St
      state: Colorado
      zipCode: 82433,USA
    Air Miles: 24
    Creation Date: 11/12/2022,5:00
   -
    ID: 14
    Name: Mr
    Type: personal
    Address:
      streetAddress: 123 Green St
      state: Colorado
      zipCode: 82433,USA
    Air Miles: 24
    Creation Date: 11/12/2022,5:00

